# https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
# https://github.com/virtualelephant/vsphere-kubernetes/blob/master/ansible/cilium-install.yml#L57
# ansible .yml files define what tasks/operations to run
---
- hosts: all # run on the "all" hosts category from ansible-hosts.txt

  # become means be superuser
  become: true
  remote_user: tebeco

  vars_files:
    - ansible-vars.yml

  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - libseccomp2

    - name: Enable overlay and br_netfilter
      command: sudo modprobe overlay && sudo modprobe br_netfilter

    - name: Enable overlay and br_netfilter in containerd.conf
      copy:
        dest: "/etc/modules-load.d/containerd.conf"
        content: |
          overlay
          br_netfilter

    - name: configure forward and bridge on ipv4/6 in k8s-cri-containerd.conf
      copy:
        dest: "/etc/sysctl.d/k8s-cri-containerd.conf"
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: configure forward and bridge on ipv4/6 in k8s-cri-containerd.conf
      copy:
        dest: "/etc/sysctl.d/k8s-cri-containerd.conf"
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: install
      shell: |
        echo 10.0.0.10 $(hostname) | sudo tee -a /etc/hosts
        CONTAINERD_VERSION="1.6.6"
        RUNC_VERSION="1.1.3"
        CNI_VERSION="1.1.1"
        KUBERNETES_VERSION="1.24.0-00"

        sudo apt-get update -y
        sudo apt-get install -y ca-certificates \
                                curl \
                                apt-transport-https \
                                libseccomp2
                                
        sudo modprobe overlay
        sudo modprobe br_netfilter
        sudo sysctl --system

        curl -LO https://github.com/containerd/containerd/releases/download/v$CONTAINERD_VERSION/containerd-$CONTAINERD_VERSION-linux-amd64.tar.gz
        sudo tar Cxzvf /usr/local containerd-$CONTAINERD_VERSION-linux-amd64.tar.gz
        curl -LO https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
        sudo cp containerd.service /lib/systemd/system/
        sudo systemctl daemon-reload
        sudo systemctl enable --now containerd
        curl -LO https://github.com/opencontainers/runc/releases/download/v$RUNC_VERSION/runc.amd64
        sudo install -m 755 runc.amd64 /usr/local/sbin/runc
        curl -LO https://github.com/containernetworking/plugins/releases/download/v$CNI_VERSION/cni-plugins-linux-amd64-v$CNI_VERSION.tgz
        sudo mkdir -p /opt/cni/bin
        sudo tar Cxzvf /opt/cni/bin cni-plugins-linux-amd64-v$CNI_VERSION.tgz
        sudo mkdir -p /etc/containerd
        sudo containerd config default | sudo tee /etc/containerd/config.toml
        sudo sed -i 's/            SystemdCgroup = false/            SystemdCgroup = true/' /etc/containerd/config.toml
        sudo systemctl restart containerd

        sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y kubelet=$KUBERNETES_VERSION \
                                kubeadm=$KUBERNETES_VERSION \
                                kubectl=$KUBERNETES_VERSION
        sudo apt-mark hold kubelet=$KUBERNETES_VERSION kubeadm=$KUBERNETES_VERSION kubectl=$KUBERNETES_VERSION

    - name: make sure containerd (re)start with proper conf/args
      copy:
        dest: "/etc/systemd/system/kubelet.service.d/0-containerd.conf"
        content: |
          [Service]
          Environment="KUBELET_EXTRA_ARGS=--container-runtime=remote --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock"

    - name: systemctl daemon-reload
      shell: sudo systemctl daemon-reload
- hosts: kube_server
  become: true
  remote_user: tebeco

  vars_files:
    - ansible-vars.yml

  tasks:
    - name: Initialize Kubernetes cluster
      command: "sudo kubeadm init --apiserver-advertise-address={{master_ip}} --apiserver-cert-extra-sans={{master_ip}} --pod-network-cidr={{pod_cidr}} --node-name={{ansible_hostname}}"
      args:
        creates: /etc/kubernetes/admin.conf # skip this task if the file already exists
      register: kube_init

    - name: show kube init info
      debug:
        var: kube_init

    - name: Create .kube directory in user home
      file:
        path: "{{ home_dir }}/.kube"
        state: directory
        owner: 1000
        group: 1000

    - name: Configure .kube/config files in user home
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ home_dir }}/.kube/config"
        remote_src: yes
        owner: 1000
        group: 1000

    - name: restart kubelet for config changes
      service:
        name: kubelet
        state: restarted

    - name: get calico networking
      get_url:
        url: https://projectcalico.docs.tigera.io/manifests/calico.yaml
        dest: "{{ home_dir }}/calico.yaml"

    - name: apply calico networking
      become: no
      command: kubectl apply -f "{{ home_dir }}/calico.yaml"

    - name: get dashboard
      get_url:
        url: https://raw.githubusercontent.com/kubernetes/dashboard/v{{kubernetes_dashboard_version}}/aio/deploy/recommended.yaml
        dest: "{{ home_dir }}/dashboard.yaml"

    - name: apply dashboard
      become: no
      command: kubectl apply -f "{{ home_dir }}/dashboard.yaml"
